/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccessDeltaSectionDto { 
    key: string;
    /**
     * The level held before the change; absent when there was none.
     */
    from?: AccessDeltaSectionDto.FromEnum;
    /**
     * The level held after; absent when the section closes.
     */
    to?: AccessDeltaSectionDto.ToEnum;
}
export namespace AccessDeltaSectionDto {
    export const FromEnum = {
        Full: 'full',
        ReadOnly: 'read-only'
    } as const;
    export type FromEnum = typeof FromEnum[keyof typeof FromEnum];
    export const ToEnum = {
        Full: 'full',
        ReadOnly: 'read-only'
    } as const;
    export type ToEnum = typeof ToEnum[keyof typeof ToEnum];
}


