/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgentIdentityDto { 
    userId: string;
    userName: string;
    name?: string;
    /**
     * The account on this instance the identity acts as, which is what its rows in the activity register are keyed by. Null until it has authenticated once: the local account is created on the first token, and minting one earlier would invent an account for something that has never arrived.
     */
    fluiUserId: string | null;
}

