/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppMetricsDataPointDto } from './appMetricsDataPointDto';


export interface AppMetricsHistoryDto { 
    /**
     * Application ID
     */
    app_id: string;
    /**
     * Application name
     */
    app_name: string;
    /**
     * Kubernetes namespace
     */
    namespace: string;
    data_points: Array<AppMetricsDataPointDto>;
}

