/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppCpuMetricsDto } from './appCpuMetricsDto';
import { AppStatusMetricsDto } from './appStatusMetricsDto';
import { AppMemoryMetricsDto } from './appMemoryMetricsDto';
import { AppNetworkMetricsDto } from './appNetworkMetricsDto';
import { ReplicaMetricsDto } from './replicaMetricsDto';
import { AppHealthStatusDto } from './appHealthStatusDto';
import { AppPodPhaseDto } from './appPodPhaseDto';


export interface AppMetricsDto { 
    /**
     * Application ID (from DB)
     */
    app_id: string;
    /**
     * Application name (maps to K8s app.kubernetes.io/name label)
     */
    app_name: string;
    /**
     * Kubernetes namespace
     */
    namespace: string;
    cpu: AppCpuMetricsDto;
    memory: AppMemoryMetricsDto;
    network: AppNetworkMetricsDto;
    status: AppStatusMetricsDto;
    /**
     * Pod counts by phase
     */
    pods: Array<AppPodPhaseDto>;
    /**
     * Per-replica metrics breakdown (one entry per running pod)
     */
    replicas: Array<ReplicaMetricsDto>;
    /**
     * Health status derived from K8s readiness probe state
     */
    health?: AppHealthStatusDto | null;
}

