/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppRemovalResponseDto { 
    /**
     * Which removal actually ran: the whole catalog install, or this application on its own.
     */
    removed: AppRemovalResponseDto.RemovedEnum;
    /**
     * The async operation to follow. Empty only for an install that was already removed before this call.
     */
    operationId: string;
    /**
     * Status of that operation when it was returned.
     */
    status: string;
    /**
     * True only when nothing is left to wait for.
     */
    done: boolean;
    /**
     * Set when the removal was already underway or complete, so the caller knows nothing new was started.
     */
    alreadyUnderway?: boolean;
    /**
     * Human-readable label for a progress widget.
     */
    label?: string;
}
export namespace AppRemovalResponseDto {
    export const RemovedEnum = {
        CatalogInstall: 'catalog-install',
        Application: 'application'
    } as const;
    export type RemovedEnum = typeof RemovedEnum[keyof typeof RemovedEnum];
}


