/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AttachClusterToVNetResponseDto { 
    /**
     * Operation ID for WebSocket subscription
     */
    operationId: string;
    /**
     * Cluster ID
     */
    clusterId: string;
    status: string;
    /**
     * Subscribe via WebSocket namespace /infrastructure with event subscribe:operation { operationId } to receive progress.
     */
    websocketNamespace: string;
}

