/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BuildResourceCheckDto { 
    status: BuildResourceCheckDto.StatusEnum;
    availableCpu?: string;
    availableMemory?: string;
}
export namespace BuildResourceCheckDto {
    export const StatusEnum = {
        Ok: 'ok',
        AutoscalingRequired: 'autoscaling_required',
        Insufficient: 'insufficient',
        Unknown: 'unknown'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


