/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CAControllerGenerateTestCertificate200Response { 
    /**
     * ED25519 private key (PEM format)
     */
    privateKey?: string;
    /**
     * SSH certificate signed by CA
     */
    certificate?: string;
    /**
     * Certificate expiration time
     */
    expiresAt?: string;
    /**
     * Valid principals (usernames)
     */
    principals?: Array<string>;
    /**
     * Command line usage instructions
     */
    instructions?: string;
}

