/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CapacityMasterDto { 
    nodeName: string;
    /**
     * Provider server type (e.g. cx22, DEV1-S)
     */
    serverType: string;
    /**
     * Allocatable CPU in millicores
     */
    allocatableCpuMillicores: number;
    /**
     * Allocatable memory in MiB
     */
    allocatableMemoryMi: number;
    /**
     * Sum of pod CPU requests on master in millicores
     */
    usedCpuMillicores: number;
    /**
     * Sum of pod memory requests on master in MiB
     */
    usedMemoryMi: number;
    freeCpuMillicores: number;
    freeMemoryMi: number;
    /**
     * Monthly cost of current server type in EUR (net)
     */
    monthlyCostEur?: string;
}

