/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CapacityComponentDto { 
    /**
     * What the numbers are about: \"unit `.`\", \"service `postgres`\"
     */
    label: string;
    unit: object | null;
    cpuRequestMillicores: number;
    memoryLimitMebibytes: number;
    replicas: number;
    /**
     * Where these numbers come from — a catalog block that declares them, or the platform default a unit with no declared resources is deployed with
     */
    basis: string;
}

