/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatalogDomainSpecDto } from './catalogDomainSpecDto';
import { CatalogDependencyDto } from './catalogDependencyDto';
import { CatalogEditableEnvDto } from './catalogEditableEnvDto';
import { CatalogUserInputPromptDto } from './catalogUserInputPromptDto';
import { CatalogResourcesDto } from './catalogResourcesDto';


export interface CatalogDetailResponseDto { 
    id: string;
    slug: string;
    name: string;
    version: string;
    category: string;
    /**
     * Macro-category for top-level menu placement (DATABASE, APPLICATION, TOOL, SYSTEM).
     */
    appKind: CatalogDetailResponseDto.AppKindEnum;
    appType: CatalogDetailResponseDto.AppTypeEnum;
    tags: Array<string>;
    description?: string;
    license?: string;
    iconUrl?: string;
    links?: object;
    ratings?: object;
    alternativeTo: Array<string>;
    /**
     * ISO date (YYYY-MM-DD) of the last time this catalog manifest was reviewed or edited. Dashboards can use this to show \"Maintained N months ago\" and warn about stale entries.
     */
    maintainedAt?: string;
    /**
     * Path to append to the resolvedFqdn when building the \"Open app\" link. Default \"/\". Use to redirect users past the root when the root does not serve a UI (e.g. PocketBase → \"/_/\", Jupyter → \"/lab\"). Frontend MUST honor this: href = https://${resolvedFqdn}${entrypointPath ?? \"/\"}
     */
    entrypointPath?: string;
    /**
     * Building-block slugs this app is a client of (e.g. pgweb → [\"postgresql\"], dbgate → [\"mariadb\",\"postgresql\",\"valkey\"]). Empty array if not a client.
     */
    clientFor: Array<string>;
    /**
     * Subset of clientFor: BB slugs for which this app is the recommended/default client. The dashboard pre-selects the default in a \"pick a client\" picker.
     */
    clientDefaultFor: Array<string>;
    userInputPrompts: Array<CatalogUserInputPromptDto>;
    editableEnv: Array<CatalogEditableEnvDto>;
    dependencies: Array<CatalogDependencyDto>;
    /**
     * Resource footprint declared by the manifest. Use requests for the capacity-check call; limits are informational (UI can show \"up to X memory\").
     */
    resources: CatalogResourcesDto;
    /**
     * Default replica count from the manifest (horizontal.min or 1 if HPA is disabled). Multiply requests by this when doing capacity checks.
     */
    replicas: number;
    /**
     * True when the manifest declares at least one port with `expose: true` AND `exposure` is `public`. False for building blocks, for standalone apps with `exposure: internal`, and for any app whose ports are all internal. The install wizard MUST skip the Domain step when false; the app detail page MUST hide the \"App Endpoints\" / DNS / Certificate tabs.
     */
    exposesPublicEndpoint: boolean;
    /**
     * Manifest-declared domain/endpoint defaults. Drives the initial values of the install wizard \"Domain\" step. Omitted when the manifest does not declare `spec.domain` or when `exposesPublicEndpoint=false`.
     */
    domain?: CatalogDomainSpecDto;
    /**
     * How this catalog app is reached once installed. `public` (default) creates Ingress + Certificate + DNS on a public hostname. `internal` skips all public exposure: the app lives only on a ClusterIP Service and is reachable only from the Flui dashboard via the ForwardAuth proxy on a wildcard internal hostname. Building blocks are always reported as `internal` regardless of their manifest.
     */
    exposure: CatalogDetailResponseDto.ExposureEnum;
    /**
     * When false, the install wizard must not offer the Internal exposure toggle. Omitted (true) for web UIs; explicitly false for infrastructure apps (queues, proxies, caches) where the ForwardAuth proxy makes no sense. Always false for building blocks.
     */
    privatizable?: boolean;
    /**
     * Kubernetes workload kind Flui will use for this app. Building blocks run as StatefulSet (stable identity, per-pod PVC, headless service); everything else is Deployment. Useful for UI hints (\"This app uses persistent storage and ordered startup\").
     */
    workloadKind: CatalogDetailResponseDto.WorkloadKindEnum;
    /**
     * How the app stores data once installed. \"shared\" lets the PVC ride on the cluster-wide flui-shared volume (works on any node). \"dedicated\" pins the pod to one node so the data sits on local disk there — used by databases that need real fsync/locking. The install wizard should surface this so users know in advance that resizing the host node will briefly stop the app.
     */
    persistenceScope: CatalogDetailResponseDto.PersistenceScopeEnum;
    /**
     * Primary container port the app listens on (first entry in spec.ports). Useful when the app is internal-only and the UI wants to show \"postgresql-xxx-svc.ns.svc.cluster.local:5432\". Undefined if the manifest declares no ports.
     */
    primaryPort?: number;
    /**
     * When present, this app declares runtime linking to one or more building blocks (e.g. pgweb ↔ postgresql, dbgate ↔ mariadb/postgresql/valkey). One entry per BB target. The FE should offer a \"Connect\" action post-install: POST /catalog/installs/:id/connect body { targetInstallId } where targetInstallId is a running BB install whose catalog slug matches one of the listed `ref`s. envMapping is resolved entirely server-side (envs via secretKeyRef to the BB Secret — passwords never leave the cluster), the FE does NOT need to surface it in any form.
     */
    linkedBuildingBlocks?: Array<Array<string>>;
    /**
     * True when this catalog app can be installed on the cluster passed via `?clusterId=`. Currently the only reason for false is that the app is `exposure: internal` and the cluster has no internal hosting (DNS / wildcard issuer / wildcard internal record). When the request omits `clusterId`, this is always true (no context to discriminate). Use this to disable the install button without attempting the call.
     */
    installable: boolean;
    /**
     * Stable code naming the reason `installable` is false. Same code returned by POST /catalog/:slug/install when it rejects.
     */
    notInstallableReason?: CatalogDetailResponseDto.NotInstallableReasonEnum;
    /**
     * Granular list of missing prerequisites. Same shape returned by GET /catalog/clusters/:id/capabilities → internalHostingMissing.
     */
    notInstallableDetails?: Array<CatalogDetailResponseDto.NotInstallableDetailsEnum>;
}
export namespace CatalogDetailResponseDto {
    export const AppKindEnum = {
        Database: 'DATABASE',
        Application: 'APPLICATION',
        Tool: 'TOOL',
        System: 'SYSTEM'
    } as const;
    export type AppKindEnum = typeof AppKindEnum[keyof typeof AppKindEnum];
    export const AppTypeEnum = {
        Standalone: 'standalone',
        BuildingBlock: 'building-block',
        Composed: 'composed'
    } as const;
    export type AppTypeEnum = typeof AppTypeEnum[keyof typeof AppTypeEnum];
    export const ExposureEnum = {
        Public: 'public',
        Internal: 'internal'
    } as const;
    export type ExposureEnum = typeof ExposureEnum[keyof typeof ExposureEnum];
    export const WorkloadKindEnum = {
        Deployment: 'Deployment',
        StatefulSet: 'StatefulSet'
    } as const;
    export type WorkloadKindEnum = typeof WorkloadKindEnum[keyof typeof WorkloadKindEnum];
    export const PersistenceScopeEnum = {
        Shared: 'shared',
        Dedicated: 'dedicated'
    } as const;
    export type PersistenceScopeEnum = typeof PersistenceScopeEnum[keyof typeof PersistenceScopeEnum];
    export const NotInstallableReasonEnum = {
        InternalHostingNotAvailable: 'INTERNAL_HOSTING_NOT_AVAILABLE'
    } as const;
    export type NotInstallableReasonEnum = typeof NotInstallableReasonEnum[keyof typeof NotInstallableReasonEnum];
    export const NotInstallableDetailsEnum = {
        DnsZone: 'dns_zone',
        WildcardIssuer: 'wildcard_issuer',
        InternalWildcardDns: 'internal_wildcard_dns'
    } as const;
    export type NotInstallableDetailsEnum = typeof NotInstallableDetailsEnum[keyof typeof NotInstallableDetailsEnum];
}


