/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CatalogUserInputPromptDto { 
    name: string;
    label?: string;
    'default'?: string;
    sensitive: boolean;
    description?: string;
    placeholder?: string;
    /**
     * JavaScript regex source (no surrounding slashes). FE must validate client-side before submitting.
     */
    pattern?: string;
    /**
     * Human-readable description of the pattern, to display when validation fails.
     */
    patternDescription?: string;
    minLength?: number;
    maxLength?: number;
    /**
     * When true the FE must render a second \"confirm\" field that has to match.
     */
    confirm?: boolean;
    /**
     * Hint for the FE to pick the right input type and keyboard autocomplete.
     */
    format?: CatalogUserInputPromptDto.FormatEnum;
}
export namespace CatalogUserInputPromptDto {
    export const FormatEnum = {
        Email: 'email',
        Url: 'url',
        Password: 'password',
        Text: 'text'
    } as const;
    export type FormatEnum = typeof FormatEnum[keyof typeof FormatEnum];
}


