/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatalogDetailResponseDto } from './catalogDetailResponseDto';


export interface CatalogValidateResponseDto { 
    valid: boolean;
    errors?: Array<string>;
    /**
     * Parsed canonical manifest. Present only when valid=true. Same shape that would be persisted in catalog_app_definitions.manifest.
     */
    manifest?: object;
    /**
     * sha256 of the canonical JSON serialization of the parsed manifest. Present only when valid=true.
     */
    checksum?: string;
    /**
     * Same shape the dashboard uses for the GET /catalog/:slug detail endpoint. Lets the caller preview how the app card would render without committing.
     */
    preview?: CatalogDetailResponseDto;
}

