/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClusterDnsZoneControllerGetIssuers200ResponseInner { 
    name?: string;
    ready?: boolean;
    email?: string | null;
    /**
     * http01 = standard domains only. combined = dns01 for wildcard (*.zone) + http01 fallback for all other domains.
     */
    solverType?: ClusterDnsZoneControllerGetIssuers200ResponseInner.SolverTypeEnum | null;
    /**
     * Status message from cert-manager (useful when ready is false)
     */
    message?: string | null;
}
export namespace ClusterDnsZoneControllerGetIssuers200ResponseInner {
    export const SolverTypeEnum = {
        Http01: 'http01',
        Dns01: 'dns01',
        Combined: 'combined'
    } as const;
    export type SolverTypeEnum = typeof SolverTypeEnum[keyof typeof SolverTypeEnum];
}


