/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClusterStoragePvcSummaryDto { 
    /**
     * Total PVCs bound to flui-shared storage class
     */
    bound: number;
    /**
     * Sum of requested storage in GB across bound PVCs
     */
    requestedGb: number;
    /**
     * Per-namespace breakdown of bound PVC counts
     */
    byNamespace: { [key: string]: number; };
}

