/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClusterPowerOperationResponseDto { 
    /**
     * Operation ID for tracking
     */
    operation_id: string;
    /**
     * Cluster ID
     */
    cluster_id: string;
    /**
     * Operation status
     */
    status: ClusterPowerOperationResponseDto.StatusEnum;
    /**
     * Estimated duration for completion
     */
    estimated_duration: string;
    /**
     * Operation creation timestamp
     */
    created_at: string;
}
export namespace ClusterPowerOperationResponseDto {
    export const StatusEnum = {
        Pending: 'pending'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


