/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MailConnectionConfigDto } from './mailConnectionConfigDto';


export interface ConnectMailProviderDto { 
    provider: ConnectMailProviderDto.ProviderEnum;
    /**
     * What this sender carries. One provider per scope, and never the same account for both — a suspension caused by a mailing list would take password resets with it.
     */
    scope: ConnectMailProviderDto.ScopeEnum;
    /**
     * What you call it. Never used to resolve anything.
     */
    label?: string;
    /**
     * The domain to send from. Given one, Flui registers it with the provider and publishes the records it asks for.
     */
    sendingDomain?: string;
    /**
     * The API key or relay password. Not needed for Scaleway, which reuses the compute key already connected. Stored encrypted and never returned.
     */
    secret?: string;
    config?: MailConnectionConfigDto;
    /**
     * Start sending through this one immediately. Left out, a provider is stored but only takes the scope if nothing else holds it — adding a second provider to try it out must not move live password resets onto a domain that has not finished verifying.
     */
    activate?: boolean;
}
export namespace ConnectMailProviderDto {
    export const ProviderEnum = {
        ScalewayTem: 'scaleway-tem',
        Brevo: 'brevo',
        Zeptomail: 'zeptomail',
        Smtp: 'smtp'
    } as const;
    export type ProviderEnum = typeof ProviderEnum[keyof typeof ProviderEnum];
    export const ScopeEnum = {
        Transactional: 'transactional',
        Bulk: 'bulk'
    } as const;
    export type ScopeEnum = typeof ScopeEnum[keyof typeof ScopeEnum];
}


