/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateRestoreJobDto { 
    artifactId: string;
    sourceDestinationId: string;
    targetClusterId: string;
    targetKind: CreateRestoreJobDto.TargetKindEnum;
    targetSelector?: object;
    strategy?: CreateRestoreJobDto.StrategyEnum;
}
export namespace CreateRestoreJobDto {
    export const TargetKindEnum = {
        Cluster: 'cluster',
        Namespace: 'namespace',
        Application: 'application',
        Observability: 'observability'
    } as const;
    export type TargetKindEnum = typeof TargetKindEnum[keyof typeof TargetKindEnum];
    export const StrategyEnum = {
        VeleroRebuild: 'velero_rebuild',
        OsSnapshot: 'os_snapshot'
    } as const;
    export type StrategyEnum = typeof StrategyEnum[keyof typeof StrategyEnum];
}


