/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RestoreTargetSelectorDto } from './restoreTargetSelectorDto';


export interface CreateRestoreJobDto { 
    artifactId: string;
    sourceDestinationId: string;
    targetClusterId: string;
    targetKind: CreateRestoreJobDto.TargetKindEnum;
    /**
     * Beside the original (`new`) or onto it, replacing what is there (`existing`). Required for cluster, namespace and application restores, where both are possible and the old default was neither. Derived for the engines that have only one meaning: a database PITR always builds a new install.
     */
    placement?: CreateRestoreJobDto.PlacementEnum;
    targetSelector?: RestoreTargetSelectorDto;
    strategy?: CreateRestoreJobDto.StrategyEnum;
    /**
     * PG_PITR only: ISO-8601 instant to recover to; omit for latest (end of WAL).
     */
    recoveryTargetTime?: string;
}
export namespace CreateRestoreJobDto {
    export const TargetKindEnum = {
        Cluster: 'cluster',
        Namespace: 'namespace',
        Application: 'application',
        Control: 'control',
        Observability: 'observability',
        Database: 'database'
    } as const;
    export type TargetKindEnum = typeof TargetKindEnum[keyof typeof TargetKindEnum];
    export const PlacementEnum = {
        New: 'new',
        Existing: 'existing'
    } as const;
    export type PlacementEnum = typeof PlacementEnum[keyof typeof PlacementEnum];
    export const StrategyEnum = {
        VeleroRebuild: 'velero_rebuild',
        OsSnapshot: 'os_snapshot',
        PgPitr: 'pg_pitr',
        MariadbPitr: 'mariadb_pitr'
    } as const;
    export type StrategyEnum = typeof StrategyEnum[keyof typeof StrategyEnum];
}


