/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EvidenceDto } from './evidenceDto';


export interface DependencySignalDto { 
    /**
     * What kind of reading produced this signal
     */
    kind: object;
    /**
     * The token read, verbatim
     */
    observed: string;
    engine: string | null;
    family: object | null;
    /**
     * The unit this belongs to; null means \"this repository\"
     */
    unit: object | null;
    injectionKeys: Array<string>;
    localName: string | null;
    confidence: DependencySignalDto.ConfidenceEnum;
    source: string;
    evidence: Array<EvidenceDto>;
    variantNote?: string;
    dependencyScope?: object;
}
export namespace DependencySignalDto {
    export const ConfidenceEnum = {
        Declared: 'declared',
        Derived: 'derived',
        Circumstantial: 'circumstantial'
    } as const;
    export type ConfidenceEnum = typeof ConfidenceEnum[keyof typeof ConfidenceEnum];
}


