/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DistributionAppDto } from './distributionAppDto';
import { DistributionNodeDto } from './distributionNodeDto';


export interface DistributionClusterDto { 
    id: string;
    name: string;
    provider: DistributionClusterDto.ProviderEnum;
    region: string;
    status: DistributionClusterDto.StatusEnum;
    clusterType: DistributionClusterDto.ClusterTypeEnum;
    nodes: Array<DistributionNodeDto>;
    apps: Array<DistributionAppDto>;
    totalApps: number;
    /**
     * Sum of replicas across all apps
     */
    totalReplicas: number;
}
export namespace DistributionClusterDto {
    export const ProviderEnum = {
        Contabo: 'contabo',
        Hetzner: 'hetzner',
        Scaleway: 'scaleway'
    } as const;
    export type ProviderEnum = typeof ProviderEnum[keyof typeof ProviderEnum];
    export const StatusEnum = {
        Creating: 'creating',
        Ready: 'ready',
        Scaling: 'scaling',
        Stopped: 'stopped',
        Error: 'error',
        Deleting: 'deleting',
        DeletionFailed: 'deletion_failed',
        Deleted: 'deleted'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const ClusterTypeEnum = {
        Control: 'control',
        Workload: 'workload',
        Observability: 'observability'
    } as const;
    export type ClusterTypeEnum = typeof ClusterTypeEnum[keyof typeof ClusterTypeEnum];
}


