/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FirewallReconciliationDetail { 
    /**
     * Provider firewall ID
     */
    providerFirewallId: string;
    /**
     * Firewall name
     */
    name: string;
    /**
     * Whether firewall was matched to a template
     */
    matched: boolean;
    /**
     * Template ID if matched
     */
    templateId?: string;
    /**
     * Template name if matched
     */
    templateName?: string;
}

