/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MailDomainSummaryDto { 
    domain: string;
    spf: MailDomainSummaryDto.SpfEnum;
    dkim: MailDomainSummaryDto.DkimEnum;
    dmarc: MailDomainSummaryDto.DmarcEnum;
    /**
     * The provider\'s own verification, which is not what DNS says. Records can be correct and published while the provider has not re-checked them yet.
     */
    verified: boolean;
    sent: number;
}
export namespace MailDomainSummaryDto {
    export const SpfEnum = {
        Ok: 'ok',
        Missing: 'missing',
        Mismatch: 'mismatch'
    } as const;
    export type SpfEnum = typeof SpfEnum[keyof typeof SpfEnum];
    export const DkimEnum = {
        Ok: 'ok',
        Missing: 'missing',
        Mismatch: 'mismatch'
    } as const;
    export type DkimEnum = typeof DkimEnum[keyof typeof DkimEnum];
    export const DmarcEnum = {
        Ok: 'ok',
        Missing: 'missing',
        Mismatch: 'mismatch'
    } as const;
    export type DmarcEnum = typeof DmarcEnum[keyof typeof DmarcEnum];
}


