/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MailObservabilityDto } from './mailObservabilityDto';
import { MailConnectionDto } from './mailConnectionDto';


export interface MailConnectResultDto { 
    connection: MailConnectionDto;
    /**
     * Whether this connection is now the one sending. False when the scope already had a provider and takeover was not asked for — it is stored, ready to be switched to.
     */
    activated: boolean;
    observability: MailObservabilityDto;
    /**
     * What was published, and what is still outstanding.
     */
    domain: object | null;
    /**
     * Whether the delivery-event webhook is live.
     */
    webhook: object;
    readiness: object | null;
    /**
     * Everything a person still has to do, in the order it blocks the rest.
     */
    manualSteps: Array<string>;
}

