/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MailKpiDto { 
    id: MailKpiDto.IdEnum;
    count: number;
    /**
     * Share of all messages in the window, 0..1. Null for `sent`, the denominator.
     */
    rate: number | null;
    previousCount: number;
    previousRate: number | null;
    /**
     * Change against the preceding window: the difference of the two rates for a rate KPI, relative change for `sent`. Null when the baseline held nothing — a fresh install has no history, and reporting that as +100% invents a trend out of an empty table.
     */
    delta: number | null;
    /**
     * Complaint thresholds are Google\'s published ones (0.10% target, 0.30% ceiling). Bounce thresholds are ours and advisory — Google publishes none.
     */
    tone: MailKpiDto.ToneEnum;
}
export namespace MailKpiDto {
    export const IdEnum = {
        Sent: 'sent',
        Delivered: 'delivered',
        Bounced: 'bounced',
        Complained: 'complained'
    } as const;
    export type IdEnum = typeof IdEnum[keyof typeof IdEnum];
    export const ToneEnum = {
        Neutral: 'neutral',
        Warn: 'warn',
        Bad: 'bad'
    } as const;
    export type ToneEnum = typeof ToneEnum[keyof typeof ToneEnum];
}


