/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MailWebhookResultDto { 
    registered: boolean;
    url?: string;
    /**
     * Why not, in the words shown on the console.
     */
    reason?: string;
}

