/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NetworkingConfigDto { 
    /**
     * Application port
     */
    port: number;
    /**
     * Protocol
     */
    protocol: NetworkingConfigDto.ProtocolEnum;
    /**
     * Whether ingress is enabled
     */
    ingressEnabled?: boolean;
    /**
     * Custom domain
     */
    domain?: string;
}
export namespace NetworkingConfigDto {
    export const ProtocolEnum = {
        Http: 'http',
        Https: 'https'
    } as const;
    export type ProtocolEnum = typeof ProtocolEnum[keyof typeof ProtocolEnum];
}


