/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObservabilityClusterControllerCreateLokiDatasource201ResponseDatasource } from './observabilityClusterControllerCreateLokiDatasource201ResponseDatasource';


export interface ObservabilityClusterControllerCreateLokiDatasource201Response { 
    success?: boolean;
    message?: string;
    datasource?: ObservabilityClusterControllerCreateLokiDatasource201ResponseDatasource;
}

