/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OidcReadinessDto { 
    /**
     * True when the OIDC client has been provisioned in the identity provider and the API has the audience/client_id configured
     */
    ready: boolean;
}

