/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PackageCacheEntryDto { 
    /**
     * Cache mount ID set by railpack — e.g. pnpm, maven, nuget, gradle, pip
     */
    id: string;
    mountPath: string;
    sizeBytes: number;
    humanSize: string;
    reclaimable: boolean;
    lastUsed: string | null;
}

