/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlatformUpdateAdvisoryDto { 
    /**
     * A blocker means the release cannot be applied from here; the reason is in the detail.
     */
    level: PlatformUpdateAdvisoryDto.LevelEnum;
    title: string;
    detail: string;
}
export namespace PlatformUpdateAdvisoryDto {
    export const LevelEnum = {
        Info: 'info',
        Warning: 'warning',
        Blocker: 'blocker'
    } as const;
    export type LevelEnum = typeof LevelEnum[keyof typeof LevelEnum];
}


