/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PriceDetailDto { 
    /**
     * Price without VAT
     */
    net: string;
    /**
     * Price with VAT
     */
    gross: string;
}

