/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProviderRegionDto { 
    id: string;
    name: string;
    displayName: string;
    country: string;
    available: boolean;
    flagEmoji?: string;
    location: string;
    description?: string;
    latitude?: number;
    longitude?: number;
}

