/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProviderFirewallCapabilityDto { 
    /**
     * How the node firewall is enforced: provider API (cloud edge), host nftables over SSH, or none
     */
    backend: ProviderFirewallCapabilityDto.BackendEnum;
    /**
     * True when filtering happens at the cloud edge (managed API) vs on the host
     */
    managedEdge: boolean;
    /**
     * Whether port 22 may be IP-allowlisted. Only when an out-of-band recovery channel exists (managedEdge); host-firewall hosts keep 22 open + CA-only to avoid lockout
     */
    supportsSshAllowlist: boolean;
}
export namespace ProviderFirewallCapabilityDto {
    export const BackendEnum = {
        ManagedApi: 'managed-api',
        HostNftables: 'host-nftables',
        None: 'none'
    } as const;
    export type BackendEnum = typeof BackendEnum[keyof typeof BackendEnum];
}


