/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReconcileTagsDto { 
    /**
     * Force tag update even if server already has Flui tags
     */
    force?: boolean;
    /**
     * Include firewall reconciliation. When true (default), automatically discovers and reconciles firewall attachments
     */
    includeFirewalls?: boolean;
}

