/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterAdoptionCaResponseDto { 
    fingerprint: string;
    /**
     * False until the nodes themselves trust the authority. Registering it here is the installation agreeing to it; enrolment is a separate step.
     */
    enrolledOnNodes: boolean;
    message: string;
}

