/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterCADto { 
    /**
     * SSH CA public key in OpenSSH format (ssh-ed25519 or ssh-rsa)
     */
    publicKey: string;
    /**
     * Optional name for the CA (defaults to flui-ca-{date})
     */
    name?: string;
    /**
     * If true, replaces existing active CA by setting it to inactive
     */
    replace?: boolean;
    /**
     * Optional metadata to store with the CA
     */
    metadata?: object;
}

