/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RemovalPreviewVolumeDto } from './removalPreviewVolumeDto';
import { RemovalSnapshotOfferDto } from './removalSnapshotOfferDto';
import { RemovalPreviewApplicationDto } from './removalPreviewApplicationDto';


export interface RemovalPreviewDto { 
    removes: RemovalPreviewDto.RemovesEnum;
    label: string;
    applications: Array<RemovalPreviewApplicationDto>;
    volumes: Array<RemovalPreviewVolumeDto>;
    totalBytes: number;
    totalLabel: string;
    /**
     * False when the cluster could not be read. An empty `volumes` then means \"not known\", and no surface may render it as \"no data\".
     */
    volumesKnown: boolean;
    /**
     * The one sentence every surface shows. Null only when the removal provably takes no storage with it.
     */
    dataWarning?: string;
    /**
     * Why the volumes could not be listed, when they could not.
     */
    note?: string;
    /**
     * Services this application attached, each with the way to keep its data before the removal takes it. Empty when it attached none.
     */
    snapshotOffer: Array<RemovalSnapshotOfferDto>;
}
export namespace RemovalPreviewDto {
    export const RemovesEnum = {
        CatalogInstall: 'catalog-install',
        Application: 'application'
    } as const;
    export type RemovesEnum = typeof RemovesEnum[keyof typeof RemovesEnum];
}


