/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReplicaInfoDto { 
    desired?: number;
    ready?: number;
    available?: number;
    unavailable?: number;
    updated?: number;
}

