/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResetPasswordDto { 
    /**
     * When true triggers an invite email (requires SMTP). When false a fresh temp password is generated and returned.
     */
    sendInvite: boolean;
}

