/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResourceOverrideMemoryDto { 
    /**
     * Memory request override. Accepts \"512Mi\", \"2Gi\", \"1Ti\" (binary) or \"M/G/T\" (decimal). Overrides the manifest default. If you set it below the app\'s real usage you may see OOMKilled.
     */
    request?: string;
    /**
     * Memory limit override. Same format as request. Typically >= request.
     */
    limit?: string;
}

