/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResourceConfigDto { 
    /**
     * CPU configuration
     */
    cpu: object;
    /**
     * Memory configuration
     */
    memory: object;
}

