/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScalingBoundsResponseDto { 
    /**
     * The floor, held now and always
     */
    min: number;
    /**
     * The target, approached opportunistically. Being below it buys nothing now.
     */
    desired: number;
    /**
     * How far urgency may reach right now
     */
    max: number;
}

