/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SecretsReadDto { 
    /**
     * Secret path (e.g. app/db).
     */
    path: string;
    /**
     * Specific version; default latest.
     */
    version?: number;
}

