/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MailAddressDto } from './mailAddressDto';


export interface SendMailDto { 
    /**
     * Must be on a domain the provider has verified for this account.
     */
    from: MailAddressDto;
    to: Array<MailAddressDto>;
    subject: string;
    text?: string;
    html?: string;
    /**
     * Providers draw the line at one-to-one triggered by a user action versus one-to-many, not at whether the message sells something. A driver whose terms forbid the stated scope refuses the message rather than discovering the rule from a suspension.
     */
    scope?: SendMailDto.ScopeEnum;
    /**
     * The caller\'s own correlation id. Never message content.
     */
    reference?: string;
}
export namespace SendMailDto {
    export const ScopeEnum = {
        Transactional: 'transactional',
        Bulk: 'bulk'
    } as const;
    export type ScopeEnum = typeof ScopeEnum[keyof typeof ScopeEnum];
}


