/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SystemAppDnsStatusDto } from './systemAppDnsStatusDto';


export interface SystemDnsStatusResponseDto { 
    fluiApi?: SystemAppDnsStatusDto;
    fluiWeb?: SystemAppDnsStatusDto;
    /**
     * null when auth mode is local (Zitadel not used)
     */
    zitadel?: SystemAppDnsStatusDto | null;
}

