/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrafficStatusDto { 
    rate_2xx: number | null;
    rate_3xx: number | null;
    rate_4xx: number | null;
    rate_5xx: number | null;
    /**
     * Server errors (5xx) as a percentage of all requests
     */
    server_error_percent: number | null;
    /**
     * Client errors (4xx) as a percentage of all requests
     */
    client_error_percent: number | null;
}

