/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TriggerScheduledJobResponseDto { 
    /**
     * The Job resource name created for this manual run.
     */
    jobName: string;
}

