/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EvidenceDto } from './evidenceDto';


export interface UnitVerdictDto { 
    id: string;
    readiness: UnitVerdictDto.ReadinessEnum;
    reason: string;
    /**
     * null only when this unit is deployable — nothing left to fix
     */
    remedy: string | null;
    evidence: Array<EvidenceDto>;
}
export namespace UnitVerdictDto {
    export const ReadinessEnum = {
        Blocked: 'blocked',
        NotAssessed: 'not_assessed',
        DeployablePendingInputs: 'deployable_pending_inputs',
        Deployable: 'deployable'
    } as const;
    export type ReadinessEnum = typeof ReadinessEnum[keyof typeof ReadinessEnum];
}


