/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateApiKeyApplicationsDto { 
    /**
     * The new, complete list of application ids this key may act on. Omit (or send an empty array) to lift the restriction entirely — the key then reaches every application its holder can already access, same as a key minted with no `applicationIds` at all.
     */
    applicationIds?: Array<string>;
}

