/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UseTemplateDto { 
    /**
     * Name of the new repository to create. Must be a valid GitHub repo name (alphanumeric, dashes, underscores, dots).
     */
    name: string;
    /**
     * GitHub user or organisation that will own the new repository. Defaults to the authenticated user\'s GitHub login.
     */
    owner?: string;
    /**
     * Optional description for the new repository
     */
    description?: string;
    /**
     * Whether the new repository should be created as private. Defaults to true.
     */
    'private'?: boolean;
    /**
     * When true, includes the full git history of the template. When false (default), only the latest commit is copied.
     */
    includeAllBranches?: boolean;
}

