/**
 * Flui.cloud API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VNetZoneDto { 
    /**
     * Internal zone/region identifier used in API calls
     */
    id: string;
    displayName: string;
    /**
     * Provider region IDs physically covered by this zone
     */
    coveredRegions: Array<string>;
}

